# Generated by Django 5.2.4 on 2025-07-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('univercitys', '0009_alter_classe_options_alter_department_options_and_more'),
        ('users', '0009_studentattachment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credit', models.PositiveIntegerField()),
                ('volume_horaire', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLevelSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univercitys.levelspeciality')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'unique_together': {('subject', 'level_speciality')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='level_specializations',
            field=models.ManyToManyField(related_name='subjects', through='courses.SubjectLevelSpeciality', to='univercitys.levelspeciality'),
        ),
        migrations.CreateModel(
            name='TeacherSubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='univercitys.classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.teacher')),
            ],
            options={
                'unique_together': {('year', 'teacher', 'subject', 'classe')},
            },
        ),
    ]
