# Generated by Django 5.2.4 on 2025-07-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('univercitys', '0009_alter_classe_options_alter_department_options_and_more'),
        ('users', '0009_studentattachment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectclass',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='univercitys.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='univercitys.speciality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='univercitys.classe'),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='users.teacher'),
        ),
    ]
