# Generated by Django 5.2.1 on 2025-05-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
