# Generated by Django 5.2.1 on 2025-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='email_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email', None), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='email_unique'),
        ),
    ]
