# Generated by Django 5.2.1 on 2025-05-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('univercitys', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speciality',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialitys', to='univercitys.department'),
        ),
        migrations.AddField(
            model_name='studentlevelspecialityclass',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='univercitys.class'),
        ),
        migrations.AddField(
            model_name='studentlevelspecialityclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='univercitys.level'),
        ),
        migrations.AddField(
            model_name='studentlevelspecialityclass',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='univercitys.speciality'),
        ),
        migrations.AddField(
            model_name='studentlevelspecialityclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student'),
        ),
        migrations.AddConstraint(
            model_name='studentlevelspecialityclass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delegate', True)), fields=('class_obj', 'year'), name='unique_delegate_per_class_year'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlevelspecialityclass',
            unique_together={('student', 'level', 'class_obj', 'year')},
        ),
    ]
