# Generated by Django 5.2.1 on 2025-05-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlevelspecialityclass',
            old_name='specialization',
            new_name='speciality',
        ),
    ]
