# Generated by Django 5.2.1 on 2025-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0003_rename_specialization_studentlevelspecialityclass_speciality'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classe',
        ),
        migrations.RemoveConstraint(
            model_name='studentlevelspecialityclass',
            name='unique_delegate_per_class_year',
        ),
        migrations.RenameField(
            model_name='studentlevelspecialityclass',
            old_name='class_obj',
            new_name='classe',
        ),
        migrations.AlterUniqueTogether(
            name='studentlevelspecialityclass',
            unique_together={('student', 'level', 'classe', 'year')},
        ),
        migrations.AddConstraint(
            model_name='studentlevelspecialityclass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delegate', True)), fields=('classe', 'year'), name='unique_delegate_per_class_year'),
        ),
    ]
