# Generated by Django 5.2.1 on 2025-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0004_rename_class_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='abbreviation',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='abbreviation',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='abbreviation',
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
