# Generated by Django 5.2.1 on 2025-05-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0005_alter_classe_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univercitys.level')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univercitys.speciality')),
            ],
            options={
                'unique_together': {('level', 'speciality')},
            },
        ),
        migrations.AddField(
            model_name='level',
            name='specialitys',
            field=models.ManyToManyField(null=True, related_name='levels', through='univercitys.LevelSpeciality', to='univercitys.speciality'),
        ),
    ]
