# Generated by Django 5.2.1 on 2025-05-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0006_levelspeciality_level_specialitys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='specialitys',
            field=models.ManyToManyField(related_name='levels', through='univercitys.LevelSpeciality', to='univercitys.speciality'),
        ),
    ]
