# Generated by Django 5.2.1 on 2025-06-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0007_alter_level_specialitys'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='univercitys.speciality'),
            preserve_default=False,
        ),
    ]
