# Generated by Django 5.2.4 on 2025-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univercitys', '0008_classe_speciality'),
        ('users', '0007_remove_user_email_unique_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='studentlevelspecialityclass',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentlevelspecialityclass',
            constraint=models.UniqueConstraint(fields=('student', 'year'), name='unique_student_per_year'),
        ),
    ]
